export const employees = [
  {
    id: 1,
    name: "Aino Virtanen",
    title: "HR Manager",
    salary: 4200,
    phone: "040-1234567",
    email: "aino.virtanen@example.com",
    animal: "Owl",
    startDate: "2018-04-01",
    location: "Helsinki",
    department: "Human Resources",
    skills: ["Recruiting", "Communication", "Employee Relations"],
  },
  {
    id: 2,
    name: "Mikko Korhonen",
    title: "Senior Developer",
    salary: 4800,
    phone: "050-7654321",
    email: "mikko.korhonen@example.com",
    animal: "Wolf",
    startDate: "2017-09-15",
    location: "Tampere",
    department: "Engineering",
    skills: ["JavaScript", "React", "Node.js"],
  },
  {
    id: 3,
    name: "Liisa Mäkelä",
    title: "Marketing Specialist",
    salary: 3900,
    phone: "045-9876543",
    email: "liisa.makela@example.com",
    animal: "Fox",
    startDate: "2019-02-10",
    location: "Helsinki",
    department: "Marketing",
    skills: ["Digital Marketing", "Content Creation", "Social Media"],
  },
  {
    id: 4,
    name: "Juha Nieminen",
    title: "Finance Director",
    salary: 5500,
    phone: "040-5566778",
    email: "juha.nieminen@example.com",
    animal: "Eagle",
    startDate: "2016-01-20",
    location: "Espoo",
    department: "Finance",
    skills: ["Financial Planning", "Budgeting", "Risk Management"],
  },
  {
    id: 5,
    name: "Sanna Koskinen",
    title: "UX Designer",
    salary: 4300,
    phone: "050-1122334",
    email: "sanna.koskinen@example.com",
    animal: "Dolphin",
    startDate: "2020-06-01",
    location: "Turku",
    department: "Design",
    skills: ["UI/UX Design", "Wireframing", "Prototyping"],
  },
  {
    id: 6,
    name: "Antti Järvinen",
    title: "Backend Developer",
    salary: 4600,
    phone: "045-3344556",
    email: "antti.jarvinen@example.com",
    animal: "Bear",
    startDate: "2018-11-05",
    location: "Tampere",
    department: "Engineering",
    skills: ["Python", "Django", "PostgreSQL"],
  },
  {
    id: 7,
    name: "Elina Laine",
    title: "Customer Success Manager",
    salary: 4100,
    phone: "040-9988776",
    email: "elina.laine@example.com",
    animal: "Butterfly",
    startDate: "2019-08-15",
    location: "Helsinki",
    department: "Customer Service",
    skills: ["Customer Relations", "Problem Solving", "CRM Systems"],
  },
  {
    id: 8,
    name: "Petri Heikkinen",
    title: "Project Manager",
    salary: 4700,
    phone: "050-5544332",
    email: "petri.heikkinen@example.com",
    animal: "Lion",
    startDate: "2017-03-20",
    location: "Espoo",
    department: "Operations",
    skills: ["Agile Methodologies", "Scrum", "Team Leadership"],
  },
  {
    id: 9,
    name: "Tiina Salonen",
    title: "Content Writer",
    salary: 3800,
    phone: "045-6677889",
    email: "tiina.salonen@example.com",
    animal: "Cat",
    startDate: "2020-01-10",
    location: "Helsinki",
    department: "Marketing",
    skills: ["Copywriting", "SEO", "Storytelling"],
  },
  {
    id: 10,
    name: "Matti Hakala",
    title: "Sales Representative",
    salary: 4000,
    phone: "040-2233445",
    email: "matti.hakala@example.com",
    animal: "Hawk",
    startDate: "2019-05-01",
    location: "Oulu",
    department: "Sales",
    skills: ["Negotiation", "Client Management", "Presentations"],
  },
];
